"""Track B1 — VLM baseline: moondream2 (~1.9B params).

Kept and maintained *specifically as a comparison point* against
`vlm_qwen2vl.py` — moondream2 isn't on Hailo's validated model list for the
AI HAT+ 2 / Hailo-10H target, while Qwen2-VL is (Hailo's own reference demo
uses Qwen2-VL-2B-Instruct on this exact Pi 5 + Camera Module 3 stack). This
backend stays in the repo so the two can be benchmarked head-to-head on
whatever hardware is at hand, not because it's the deployment candidate.

moondream2's `answer_question` is tuned for short, literal VQA — it ignores
multi-line structured-response instructions in favor of a one-word answer.
So detection is two single-purpose numeric questions (person count, vest
count); the GO/STOP message itself is never generated by the model — see
`messages.py` for why.
"""

from __future__ import annotations

import numpy as np

from .base import Detection, DetectionResult, VestDetector
from .messages import compliance_message

_Q_PEOPLE = "How many people are visible in this image? Answer with just a number."
_Q_VESTS = (
    "How many of the people in this image are wearing a high-visibility "
    "orange, yellow, or lime green safety vest on their body? A vest that "
    "is only held in a hand or hanging nearby does not count. Answer with "
    "just a number."
)


class MoondreamDetector(VestDetector):
    name = "vlm_moondream"

    def __init__(self, model_id: str = "vikhyatk/moondream2", device: str | None = None):
        self.model_id = model_id
        self.device = device
        self._model = None
        self._tokenizer = None

    def warmup(self) -> None:
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer

        device = self.device or ("cuda" if torch.cuda.is_available() else "cpu")
        dtype = torch.float16 if device == "cuda" else torch.float32

        self._model = AutoModelForCausalLM.from_pretrained(
            self.model_id,
            revision="2024-08-26",
            trust_remote_code=True,
            torch_dtype=dtype,
        ).to(device)
        self._model.eval()
        self._tokenizer = AutoTokenizer.from_pretrained(self.model_id, revision="2024-08-26")
        self._device = device

    def unload(self) -> None:
        import gc

        import torch

        self._model = None
        self._tokenizer = None
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    def infer(self, frame_bgr: np.ndarray) -> DetectionResult:
        if self._model is None:
            self.warmup()
        assert self._model is not None and self._tokenizer is not None

        import cv2
        from PIL import Image

        rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(rgb)
        enc_image = self._model.encode_image(image)

        n_people = _parse_int(self._model.answer_question(enc_image, _Q_PEOPLE, self._tokenizer))
        n_vests = 0
        if n_people > 0:
            n_vests = min(
                _parse_int(self._model.answer_question(enc_image, _Q_VESTS, self._tokenizer)),
                n_people,
            )

        h, w = frame_bgr.shape[:2]
        compliant = n_people > 0 and n_vests >= n_people
        detections = [
            Detection(
                bbox=(0, 0, w, h),  # whole-scene verdict, no per-person boxes from this backend
                wearing_vest=i < n_vests,
                confidence=1.0,
            )
            for i in range(n_people)
        ]
        message = compliance_message(compliant) if n_people > 0 else ""
        return DetectionResult(detections=detections, message=message)


def _parse_int(answer: str) -> int:
    """Best-effort parse of a numeric answer; falls back to 0 rather than raising
    if the model returns something unexpected."""
    import re

    match = re.search(r"\d+", answer)
    return int(match.group(0)) if match else 0
